<?php
/**
 * Created by PhpStorm.
 * User: phamc
 * Date: 4/2/2019
 * Time: 23:45
 */

namespace api\models\TheNap;


use common\Utilities\DatetimeUtils;
use common\Utilities\SessionUtils;
use yii\db\ActiveRecord;


/**
 * @property bool $ma_the
 * @property bool $seri
 * @property bool $menh_gia
 * @property bool $is_delete
 * @property string $updated_at
 * @property string $updated_by
 * @property string $created_by
 * @property string $created_at
 */
class TheNap extends ActiveRecord
{
    public static function tableName()
    {
        return '{{the_nap}}'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            ["ma_the","trim"],
            ["seri","trim"],
            ["menh_gia","trim"],
            ["is_delete","default", "value"=>0],
            ['created_at', 'default', 'value' => DatetimeUtils::getCurrentDatetime()],
            ['updated_at', 'default', 'value' => DatetimeUtils::getCurrentDatetime()],
            ['created_by', 'default', 'value' => SessionUtils::getUsername()],
            ['updated_by', 'default', 'value' => SessionUtils::getUsername()]
        ];
    }
    /*public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                try {
                    $this->auth_key = \Yii::$app->security->generateRandomString();
                } catch (Exception $e) {
                }
            }
            return true;
        }
        return false;
    }*/
}