<?php
/**
 * Created by PhpStorm.
 * User: phamc
 * Date: 4/2/2019
 * Time: 23:36
 */

namespace api\models\ChiTietHoaDon;


use api\models\HoaDon\HoaDon;
use api\models\SanPham\SanPham;
use api\models\TheNap\TheNap;
use common\Utilities\DatetimeUtils;
use common\Utilities\SessionUtils;
use yii\db\ActiveRecord;

/**
 * @property string hoa_don_id
 * @property string san_pham_id
 * @property string the_nap_id
 * @property string so_luong
 * @property bool $is_delete
 * @property string $updated_at
 * @property string $updated_by
 * @property string $created_by
 * @property string $created_at
 */
class ChiTietHoaDon extends ActiveRecord
{
    public static function tableName()
    {
        return '{{hoa_don_chi_tiet}}'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            ["hoa_don_id","trim"],
            ["san_pham_id","trim"],
            ["the_nap_id","trim"],
            ["so_luong","trim"],
            ["is_delete","default", "value"=>0],
            ['created_at', 'default', 'value' => DatetimeUtils::getCurrentDatetime()],
            ['updated_at', 'default', 'value' => DatetimeUtils::getCurrentDatetime()],
            ['created_by', 'default', 'value' => SessionUtils::getUsername()],
            ['updated_by', 'default', 'value' => SessionUtils::getUsername()]
        ];
    }
    public function getHoadon()
    {
        return $this->hasOne(HoaDon::className(),['id'=>'hoa_don_id']);
    }
    public function getSanpham()
    {
        return $this->hasOne(SanPham::className(),['id'=>'san_pham_id']);
    }
    public function getThenap()
    {
        return $this->hasOne(TheNap::className(),['id'=>'the_nap_id']);
    }
}