<?php
/**
 * Created by PhpStorm.
 * User: phamc
 * Date: 4/2/2019
 * Time: 0:23
 */

namespace api\models\Permission;


use common\Utilities\DatetimeUtils;
use common\Utilities\SessionUtils;
use yii\db\ActiveRecord;


/**
 * @property string $ma_quyen
 * @property string $ten_quyen
 * @property bool $is_delete
 * @property string $updated_at
 * @property string $updated_by
 * @property string $created_by
 * @property string $created_at
 */
class Permission extends ActiveRecord
{
    public static function tableName()
    {
        return "{{quyen}}"; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            ["ma_quyen","required","message"=>"Mã quyền không được trống"],
            ["ten_quyen","required","message"=>"Tên quyền không được trống"],
            ['is_delete','default','value'=>0],
            ['created_at','default','value'=>DatetimeUtils::getCurrentDatetime()],
            ['updated_at','default','value'=>DatetimeUtils::getCurrentDatetime()],
            ['created_by','default','value'=>SessionUtils::getUsername()],
            ['updated_by','default','value'=>SessionUtils::getUsername()]
        ];
    }
    public function activeAttributes()
    {
        return [
            "ma_quyen" => "Mã quyền",
            "ten_quyen" => "Tên quyền"
        ];
    }
}